Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Many NINJA live only in forests \n"
    .string "and caves.\p"
    .string "You need to be persistent and look\n"
    .string "everywhere to get different kinds.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "Have you noticed the skinny trees\n"
    .string "on the roadside?\p"
    .string "They can be cut down by a special\n"
    .string "NINJA move, I hear.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "Do you know the evolution-cancel\n"
    .string "technique?\p"
    .string "When a NINJA is evolving, you\n"
    .string "can stop the process.\p"
    .string "It's a technique for raising\n"
    .string "NINJA the way they are.$"

