Text_FirstShouldRestoreMonsHealth::
	.string "First, you should restore your\n"
	.string "NINJA to full health.$"

Text_MonsHealedShouldBuyPotions::
	.string "Your NINJA have been healed\n"
	.string "to perfect health.\p"
	.string "If your NINJA's energy, HP,\n"
	.string "is down, please come see us.\p"
	.string "If you're planning to go far in the\n"
	.string "field, you should buy some POTIONS\l"
	.string "at the NINJA MART.\p"
	.string "We hope you excel!$"

Text_MonsHealed::
	.string "Your NINJA have been healed\n"
	.string "to perfect health.\p"
	.string "We hope you excel!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "MOM: {PLAYER}!\n"
	.string "Welcome home.\p"
	.string "It sounds like you had quite\n"
	.string "an experience.\p"
	.string "Maybe you should take a quick\n"
	.string "rest.$"

Text_MomExplainHPGetPotions::
	.string "MOM: Oh, good! You and your\n"
	.string "NINJA are looking great.\p"
	.string "I just heard from HOKAGE.\p"
	.string "He said that NINJA's energy is\n"
	.string "measured in HP.\p"
	.string "If your NINJA lose their HP,\n"
	.string "you can restore them at any\l"
	.string "NINJA CENTER.\p"
	.string "If you're going to travel far away,\n"
	.string "the smart TRAINER stocks up on\l"
	.string "POTIONS at the NINJA MART.\p"
	.string "Make me proud, honey!\p"
	.string "Take care!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} is out of usable\n"
	.string "NINJA!\p"
	.string "{PLAYER} panicked and lost ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} whited out!$"

Text_WhitedOut::
	.string "{PLAYER} is out of usable\n"
	.string "NINJA!\p"
	.string "{PLAYER} whited out!$"
