ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
    .string "Is it true?\p"
    .string "CELADON DEPT. STORE is several\n"
    .string "times bigger than this shop?$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
    .string "I sometimes buy medicine here.\p"
    .string "But a lot of people heal NINJA\n"
    .string "with BERRIES from BERRY FOREST.\p"
    .string "After all, BERRIES are free and\n"
    .string "they never run out.$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
    .string "Those BIKERS were about to trash\n"
    .string "this NINJA MART.\p"
    .string "Am I glad they decided to leave!$"

