PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Welcome to the NINJA LEAGUE.\p"
    .string "I am KONAN of the ELITE FOUR.\p"
    .string "No one can best me when it comes\n"
    .string "to icy NINJA.\p"
    .string "Freezing moves are powerful.\p"
    .string "Your NINJA will be at my mercy\n"
    .string "when they are frozen solid.\p"
    .string "Hahaha!\n"
    .string "Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "Welcome to the NINJA LEAGUE.\p"
    .string "I, KONAN of the ELITE FOUR,\n"
    .string "have returned!\p"
    .string "You know how it goes.\n"
    .string "No one can best me when it comes\l"
    .string "to icy NINJA.\p"
    .string "Freezing moves are powerful.\p"
    .string "Your NINJA will be at my mercy\n"
    .string "when they are frozen solid.\p"
    .string "Hahaha!\n"
    .string "Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Things shouldn't be this way!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "You're better than I thought.\n"
    .string "Go on ahead.\p"
    .string "You only got a taste of the\n"
    .string "NINJA LEAGUE's power.$"

