VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "There are wicked people who will\n"
    .string "use NINJA for criminal acts.\p"
    .string "AKATSUKI traffics in rare\n"
    .string "NINJA, for example.\p"
    .string "They also abandon NINJA that\n"
    .string "they consider unpopular or useless.\p"
    .string "That's the sort of horrid people\n"
    .string "they are, AKATSUKI.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "I think NINJA can be good or\n"
    .string "bad. It depends on the TRAINER.$"

