SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
    .string "NINJA growth rates differ from\n"
    .string "species to species.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
    .string "SILPH CO. is widely known to all.\p"
    .string "It's a victim of its own fame - it\n"
    .string "attracted AKATSUKI.$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
    .string "Sigh…\n"
    .string "Wouldn't this be great?\p"
    .string "If the ELITE FOUR came and\n"
    .string "stomped AKATSUKI?$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
    .string "AKATSUKI took off!\n"
    .string "We can go out safely again!\l"
    .string "That's great!$"

