"""Naruto theme data: types, type chart, jutsu, the 40 ninjas, and how the
original Pokémon of the game map onto them.

Applied to the decompilation by tools/naruto/apply.py. This file is the
single source of truth for the theme; edit it and re-run the script.

The 17 Naruto types reuse the game's type slots, so each keeps the built-in
mechanics of its slot (weather boosts, status immunities, and whether its
moves are physical or special, which Gen 3 decides by type).
"""

# Naruto type -> game type slot. Slots before MYSTERY are physical.
TYPES = {
    'NINJA':   'NORMAL',    # physical
    'TAIJU':   'FIGHTING',  # physical, taijutsu
    'FUTON':   'FLYING',    # physical, wind release
    'BUKI':    'POISON',    # physical, weapons and poisons
    'DOTON':   'GROUND',    # physical, earth release (immune to sandstorm)
    'PUPPET':  'ROCK',      # physical
    'BEAST':   'BUG',       # physical, summons and ninja animals
    'BIJU':    'GHOST',     # physical, tailed beasts
    'SAGE':    'STEEL',     # physical, sage mode (can't be poisoned)
    'KATON':   'FIRE',      # special, fire release (sun boost, no burns)
    'SUITON':  'WATER',     # special, water release (rain boost)
    'MOKUTON': 'GRASS',     # special, wood release
    'RAITON':  'ELECTRIC',  # special, lightning release
    'GENJU':   'PSYCHIC',   # special, genjutsu
    'HYOTON':  'ICE',       # special, ice release (can't be frozen)
    'YANG':    'DRAGON',    # special, body and life force, medical ninjutsu
    'YIN':     'DARK',      # special, mind and shadows
}

# Names shown in game (at most 6 characters).
TYPE_NAMES = {
    'NINJA': 'NINJA', 'TAIJU': 'TAIJU', 'FUTON': 'FUTON', 'BUKI': 'BUKI',
    'DOTON': 'DOTON', 'PUPPET': 'PUPPET', 'BEAST': 'BEAST', 'BIJU': 'BIJU',
    'SAGE': 'SAGE', 'KATON': 'KATON', 'SUITON': 'SUITON', 'MOKUTON': 'MOKU',
    'RAITON': 'RAITON', 'GENJU': 'GENJU', 'HYOTON': 'HYOTON', 'YANG': 'YANG',
    'YIN': 'YIN',
}

# Type chart: attacker -> {defender: multiplier}; anything not listed is 1x.
SUPER, HALF, NONE = 2.0, 0.5, 0.0
TYPE_CHART = {
    # The five chakra natures: fire > wind > lightning > earth > water > fire.
    # The starters add wind > earth and earth > fire (Naruto > Sakura > Sasuke).
    'KATON':   {'FUTON': SUPER, 'HYOTON': SUPER, 'MOKUTON': SUPER, 'PUPPET': SUPER, 'BEAST': SUPER, 'SAGE': SUPER,
                'SUITON': HALF, 'KATON': HALF, 'DOTON': HALF, 'BIJU': HALF},
    'FUTON':   {'RAITON': SUPER, 'DOTON': SUPER, 'MOKUTON': SUPER,
                'KATON': HALF, 'FUTON': HALF, 'HYOTON': HALF, 'BIJU': HALF},
    'RAITON':  {'DOTON': SUPER, 'SUITON': SUPER,
                'FUTON': HALF, 'RAITON': HALF, 'MOKUTON': HALF, 'BIJU': HALF},
    'DOTON':   {'SUITON': SUPER, 'KATON': SUPER, 'BUKI': SUPER, 'SAGE': SUPER,
                'RAITON': HALF, 'MOKUTON': HALF, 'FUTON': HALF, 'BIJU': HALF},
    'SUITON':  {'KATON': SUPER, 'BUKI': SUPER,
                'DOTON': HALF, 'SUITON': HALF, 'MOKUTON': HALF, 'BIJU': HALF},
    # Advanced natures.
    'HYOTON':  {'FUTON': SUPER, 'MOKUTON': SUPER, 'DOTON': SUPER,
                'KATON': HALF, 'HYOTON': HALF},
    'MOKUTON': {'SUITON': SUPER, 'DOTON': SUPER, 'BIJU': SUPER,
                'KATON': HALF, 'MOKUTON': HALF, 'BUKI': HALF},
    # Taijutsu, weapons and puppets.
    'TAIJU':   {'NINJA': SUPER, 'PUPPET': SUPER, 'SAGE': SUPER, 'HYOTON': SUPER,
                'GENJU': HALF, 'BEAST': HALF, 'BIJU': HALF, 'BUKI': HALF},
    'BUKI':    {'PUPPET': SUPER, 'BEAST': SUPER, 'GENJU': SUPER, 'MOKUTON': SUPER,
                'DOTON': HALF, 'SAGE': HALF, 'BUKI': HALF, 'BIJU': HALF},
    'PUPPET':  {'YANG': SUPER, 'BUKI': SUPER,
                'DOTON': HALF, 'SAGE': HALF, 'PUPPET': HALF},
    'NINJA':   {'PUPPET': HALF, 'BIJU': HALF},
    # Summons and tailed beasts.
    'BEAST':   {'TAIJU': SUPER, 'YIN': SUPER,
                'KATON': HALF, 'SAGE': HALF, 'BIJU': HALF},
    'BIJU':    {'NINJA': SUPER, 'TAIJU': SUPER, 'BEAST': SUPER,
                'SAGE': HALF, 'MOKUTON': HALF},
    'SAGE':    {'BIJU': SUPER, 'GENJU': SUPER, 'YIN': SUPER,
                'SAGE': HALF, 'KATON': HALF},
    # Genjutsu and yin/yang.
    'GENJU':   {'TAIJU': SUPER, 'YANG': SUPER,
                'GENJU': HALF, 'SAGE': HALF, 'BIJU': HALF, 'YIN': HALF},
    'YIN':     {'GENJU': SUPER, 'YANG': SUPER, 'BIJU': SUPER,
                'YIN': HALF},
    'YANG':    {'YIN': SUPER, 'BUKI': SUPER,
                'YANG': HALF, 'PUPPET': HALF},
}

# Jutsu: existing moves renamed (at most 12 characters). A type given here
# replaces the move's type; effects, power and animations stay.
MOVES = {
    # Ninja basics
    'TACKLE':        ('STRIKE', None),
    'SCRATCH':       ('KUNAI SLASH', 'BUKI'),
    'GROWL':         ('KIAI', None),
    'LEER':          ('GLARE', None),
    'QUICK_ATTACK':  ('SHUNSHIN', None),
    'DOUBLE_TEAM':   ('CLONE JUTSU', None),
    'SUBSTITUTE':    ('SUBSTITUTION', None),
    'MEGA_PUNCH':    ('RASENGAN', None),
    'FOCUS_ENERGY':  ('CHAKRA FOCUS', None),
    'SMOKESCREEN':   ('SMOKE BOMB', None),
    'MIMIC':         ('COPY NINJA', None),
    'RECOVER':       ('MYSTIC PALM', None),
    'EXPLOSION':     ('ART IS BANG!', None),
    'SELF_DESTRUCT': ('CLAY BOMB', None),
    'HYPER_BEAM':    ('BIJUDAMA', 'BIJU'),
    # Taijutsu
    'KARATE_CHOP':   ('LEAF WHIRL', None),
    'LOW_KICK':      ('SWEEP KICK', None),
    'DOUBLE_KICK':   ('DYNAMIC KICK', None),
    'HI_JUMP_KICK':  ('LEAF TYPHOON', None),
    'MACH_PUNCH':    ('SWIFT FIST', None),
    'SKY_UPPERCUT':  ('FRONT LOTUS', None),
    'CROSS_CHOP':    ('HIDDEN LOTUS', None),
    'BRICK_BREAK':   ('GENTLE FIST', None),
    'BULK_UP':       ('EIGHT GATES', None),
    'FOCUS_PUNCH':   ('NIGHT GUY', None),
    'VITAL_THROW':   ('ROTATION', None),
    'DETECT':        ('BYAKUGAN', None),
    # Wind
    'GUST':          ('AIR BULLET', None),
    'WING_ATTACK':   ('WIND BLADE', None),
    'AERIAL_ACE':    ('VACUUM BLADE', None),
    'AIR_CUTTER':    ('WIND SCYTHE', None),
    'RAZOR_WIND':    ('GREAT GALE', None),
    'AEROBLAST':     ('RASENSHURIKN', None),
    # Weapons
    'POISON_STING':  ('SENBON', None),
    'SLUDGE_BOMB':   ('POISON BOMB', None),
    'SWIFT':         ('SHURIKEN', 'BUKI'),
    'PIN_MISSILE':   ('KUNAI RAIN', 'BUKI'),
    'SLASH':         ('BLADE SLASH', 'BUKI'),
    # Earth
    'MUD_SLAP':      ('MUD BULLET', None),
    'DIG':           ('HEADHUNTER', None),
    'EARTHQUAKE':    ('EARTH SPLIT', None),
    'SAND_TOMB':     ('SAND COFFIN', None),
    'ROCK_TOMB':     ('SAND BURIAL', 'DOTON'),
    # Puppets
    'ROCK_THROW':    ('PUPPET STAB', None),
    'ROCK_SLIDE':    ('PUPPET ARMY', None),
    'ANCIENT_POWER': ('CROW TRAP', None),
    # Beasts
    'FURY_CUTTER':   ('GATSUGA', None),
    'TWINEEDLE':     ('DOUBLE FANG', None),
    'MEGAHORN':      ('BEAST CHARGE', None),
    # Tailed beasts
    'NIGHT_SHADE':   ('CHAKRA WAVE', None),
    'SHADOW_BALL':   ('CHAKRA BOMB', None),
    'CONFUSE_RAY':   ('KILLER AURA', None),
    # Sage
    'METEOR_MASH':   ('FROG KUMITE', None),
    'IRON_TAIL':     ('SAGE ART', None),
    'IRON_DEFENSE':  ('SAGE MODE', None),
    # Fire
    'EMBER':         ('FIREBALL', None),
    'FLAMETHROWER':  ('PHOENIX FIRE', None),
    'FIRE_SPIN':     ('FIRE DRAGON', None),
    'FIRE_BLAST':    ('DRAGON FLAME', None),
    'OVERHEAT':      ('AMATERASU', None),
    'HEAT_WAVE':     ('ASH BURN', None),
    'WILL_O_WISP':   ('BLACK FLAME', None),
    # Water
    'WATER_GUN':     ('WATER BULLET', None),
    'HYDRO_PUMP':    ('SHARK BOMB', None),
    'WHIRLPOOL':     ('WATER PRISON', None),
    'WATER_PULSE':   ('WATER DRAGON', None),
    'MIST':          ('HIDDEN MIST', None),
    # Wood
    'VINE_WHIP':     ('WOOD WHIP', None),
    'LEECH_SEED':    ('CHAKRA DRAIN', None),
    'RAZOR_LEAF':    ('WOOD SPIKES', None),
    'GIGA_DRAIN':    ('LIFE DRAIN', None),
    'SOLAR_BEAM':    ('WOOD DRAGON', None),
    # Lightning
    'THUNDER_SHOCK': ('LIGHTNING', None),
    'THUNDERBOLT':   ('CHIDORI', None),
    'THUNDER':       ('KIRIN', None),
    'THUNDER_WAVE':  ('STUN CURRENT', None),
    'SHOCK_WAVE':    ('RAIKIRI', None),
    # Genjutsu
    'CONFUSION':     ('GENJUTSU', None),
    'PSYBEAM':       ('SHARINGAN', None),
    'PSYCHIC':       ('TSUKUYOMI', None),
    'HYPNOSIS':      ('DEMON ILLUS.', None),
    # Ice
    'ICY_WIND':      ('ICE NEEDLES', None),
    'ICE_BEAM':      ('ICE MIRRORS', None),
    # Yang
    'DRAGON_CLAW':   ('CHAKRA FIST', None),
    'DRAGON_DANCE':  ('CHAKRA SURGE', None),
    # Yin
    'CRUNCH':        ('SHADOW CHOKE', None),
    'MEAN_LOOK':     ('SHADOW BIND', 'YIN'),
    'FAINT_ATTACK':  ('SHADOW STAB', None),
}

# The ninjas. `slot` is the Pokémon whose data each one replaces (its
# species ID and National Dex number). Stats: HP, Atk, Def, Spe, SpA, SpD.
# Gender: 'M', 'F' or a female percentage. `evo`: (level, ninja key).
ROSTER = [
    dict(key='NARUTO', slot='BULBASAUR', name='NARUTO', types=['FUTON'],
         stats=(50, 58, 45, 55, 55, 55), abilities=['GUTS'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=64, evo=(16, 'NARUTO_SM'), color='YELLOW',
         moves=[(1, 'TACKLE'), (1, 'GROWL'), (6, 'DOUBLE_TEAM'), (10, 'QUICK_ATTACK'), (14, 'GUST'),
                (19, 'MEGA_PUNCH'), (25, 'FOCUS_ENERGY'), (32, 'WING_ATTACK'), (40, 'SUBSTITUTE')],
         category='HYPERACTIVE', height=14, weight=400,
         dex='A loud genin who never gives up. He\ncan make hundreds of shadow clones\nand dreams of becoming HOKAGE.',
         look='spiky blond hair, whisker marks on cheeks, orange and black jumpsuit, blue forehead protector with leaf symbol'),
    dict(key='NARUTO_SM', slot='IVYSAUR', name='NARUTO SM', types=['FUTON', 'SAGE'],
         stats=(60, 80, 60, 75, 75, 70), abilities=['GUTS'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=142, evo=(36, 'NARUTO_KCM'), color='YELLOW',
         moves=[(1, 'TACKLE'), (1, 'GROWL'), (1, 'DOUBLE_TEAM'), (1, 'QUICK_ATTACK'), (14, 'GUST'),
                (19, 'MEGA_PUNCH'), (22, 'IRON_DEFENSE'), (27, 'WING_ATTACK'), (33, 'METEOR_MASH'),
                (40, 'FOCUS_ENERGY'), (47, 'SUBSTITUTE')],
         category='SAGE', height=17, weight=600,
         dex='Trained by the toads of MT. MYOBOKU.\nIn SAGE MODE he senses nature energy\nand his eyes become like a toad\'s.',
         look='spiky blond hair, orange toad-like eye markings, red cloak with black flame pattern over orange and black outfit'),
    dict(key='NARUTO_KCM', slot='VENUSAUR', name='NARUTO KCM', types=['FUTON', 'BIJU'],
         stats=(80, 105, 78, 100, 95, 77), abilities=['GUTS'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=208, color='YELLOW',
         moves=[(1, 'TACKLE'), (1, 'GROWL'), (1, 'DOUBLE_TEAM'), (1, 'QUICK_ATTACK'), (14, 'GUST'),
                (19, 'MEGA_PUNCH'), (22, 'IRON_DEFENSE'), (27, 'WING_ATTACK'), (33, 'METEOR_MASH'),
                (39, 'AEROBLAST'), (46, 'SHADOW_BALL'), (55, 'HYPER_BEAM')],
         category='JINCHURIKI', height=17, weight=600,
         dex='Working together with the nine-tailed\nfox KURAMA, his whole body glows with\ngolden chakra.',
         look='glowing golden-orange chakra cloak covering the whole body with black swirl markings, spiky blond hair, flame-like aura'),

    dict(key='SASUKE', slot='CHARMANDER', name='SASUKE', types=['KATON'],
         stats=(47, 55, 43, 65, 60, 48), abilities=['BLAZE'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=65, evo=(16, 'SASUKE_CS'), color='BLUE',
         moves=[(1, 'SCRATCH'), (1, 'LEER'), (7, 'EMBER'), (13, 'QUICK_ATTACK'), (19, 'SWIFT'),
                (25, 'PSYBEAM'), (31, 'FIRE_SPIN'), (38, 'SLASH'), (46, 'FLAMETHROWER')],
         category='AVENGER', height=15, weight=440,
         dex='The last of the UCHIHA clan. A cool\ngenius who masters fire style and\nawakens the SHARINGAN.',
         look='black spiky hair pointing backwards, dark eyes, navy high-collar shirt with red and white fan symbol, white shorts, blue forehead protector'),
    dict(key='SASUKE_CS', slot='CHARMELEON', name='SASUKE CS', types=['KATON', 'RAITON'],
         stats=(58, 75, 58, 80, 80, 64), abilities=['BLAZE'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=142, evo=(36, 'SASUKE_MS'), color='BLUE',
         moves=[(1, 'SCRATCH'), (1, 'LEER'), (1, 'EMBER'), (13, 'QUICK_ATTACK'), (19, 'SWIFT'),
                (25, 'PSYBEAM'), (28, 'THUNDERBOLT'), (34, 'FIRE_SPIN'), (41, 'FLAMETHROWER'), (48, 'SLASH')],
         category='CURSE MARK', height=16, weight=500,
         dex='The curse mark spreads black flames\nover his skin. He channels lightning\ninto the CHIDORI.',
         look='black spiky hair, red sharingan eyes, black flame-shaped curse mark patterns spreading over his face and arms, crackling blue lightning in one hand'),
    dict(key='SASUKE_MS', slot='CHARIZARD', name='SASUKE MS', types=['KATON', 'GENJU'],
         stats=(78, 84, 78, 100, 109, 85), abilities=['BLAZE'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=209, color='BLUE',
         moves=[(1, 'SCRATCH'), (1, 'LEER'), (1, 'EMBER'), (1, 'QUICK_ATTACK'), (19, 'SWIFT'),
                (25, 'PSYBEAM'), (28, 'THUNDERBOLT'), (34, 'FIRE_SPIN'), (41, 'FLAMETHROWER'),
                (46, 'PSYCHIC'), (52, 'OVERHEAT'), (59, 'THUNDER')],
         category='MANGEKYO', height=17, weight=600,
         dex='His MANGEKYO SHARINGAN summons black\nflames that never go out and a giant\nwarrior of purple chakra.',
         look='black spiky hair, red mangekyo sharingan eyes, grey high-collar robe with rope belt, sword on his back, surrounded by purple flame aura'),

    dict(key='SAKURA', slot='SQUIRTLE', name='SAKURA', types=['DOTON'],
         stats=(48, 55, 55, 43, 45, 60), abilities=['NATURAL_CURE'], gender='F', growth='MEDIUM_SLOW',
         catch=45, exp=66, evo=(16, 'SAKURA_MN'), color='PINK',
         moves=[(1, 'TACKLE'), (1, 'LEER'), (7, 'MUD_SLAP'), (13, 'KARATE_CHOP'), (19, 'ROCK_TOMB'),
                (25, 'RECOVER'), (31, 'DIG'), (38, 'DRAGON_CLAW'), (46, 'EARTHQUAKE')],
         category='KUNOICHI', height=16, weight=450,
         dex='A clever kunoichi with perfect chakra\ncontrol. Her punches are strong enough\nto shatter the ground.',
         look='short pink hair, green eyes, red sleeveless top with white circle, black shorts, red forehead protector worn as a hairband'),
    dict(key='SAKURA_MN', slot='WARTORTLE', name='SAKURA MN', types=['DOTON', 'YANG'],
         stats=(59, 80, 70, 58, 60, 78), abilities=['NATURAL_CURE'], gender='F', growth='MEDIUM_SLOW',
         catch=45, exp=143, evo=(36, 'SAKURA_BYK'), color='PINK',
         moves=[(1, 'TACKLE'), (1, 'LEER'), (1, 'MUD_SLAP'), (13, 'KARATE_CHOP'), (19, 'ROCK_TOMB'),
                (22, 'RECOVER'), (28, 'DRAGON_CLAW'), (33, 'DIG'), (40, 'BULK_UP'), (47, 'EARTHQUAKE')],
         category='MEDIC NINJA', height=16, weight=460,
         dex='A medical ninja trained by TSUNADE.\nShe heals allies with glowing hands\nand fights with monstrous strength.',
         look='short pink hair, red top with white circle, black gloves, glowing green healing chakra on her hands'),
    dict(key='SAKURA_BYK', slot='BLASTOISE', name='SAKURA BYK', types=['DOTON', 'YANG'],
         stats=(79, 110, 95, 78, 70, 103), abilities=['NATURAL_CURE'], gender='F', growth='MEDIUM_SLOW',
         catch=45, exp=210, color='PINK',
         moves=[(1, 'TACKLE'), (1, 'LEER'), (1, 'MUD_SLAP'), (1, 'KARATE_CHOP'), (19, 'ROCK_TOMB'),
                (22, 'RECOVER'), (28, 'DRAGON_CLAW'), (33, 'DIG'), (40, 'BULK_UP'), (47, 'EARTHQUAKE'),
                (53, 'DRAGON_DANCE'), (60, 'FOCUS_PUNCH')],
         category='BYAKUGO', height=16, weight=470,
         dex='The diamond seal on her forehead is\nreleased, covering her in black lines.\nNo wound can stop her anymore.',
         look='pink hair, purple diamond mark on forehead, black line patterns spreading across her face and arms, red outfit, fist raised'),

    dict(key='STUDENT', slot='CATERPIE', name='STUDENT', types=['NINJA'],
         stats=(40, 45, 35, 50, 30, 30), abilities=['RUN_AWAY'], gender=25, growth='MEDIUM_FAST',
         catch=255, exp=39, evo=(12, 'GENIN'), color='BLUE',
         moves=[(1, 'TACKLE'), (1, 'LEER'), (5, 'SAND_ATTACK'), (9, 'SCRATCH'), (13, 'QUICK_ATTACK'),
                (18, 'SWIFT'), (25, 'DOUBLE_TEAM')],
         category='ACADEMY', height=12, weight=300,
         dex='A young student of the NINJA ACADEMY.\nIt practices throwing kunai at trees\nfrom morning until night.',
         look='young child in a plain blue tunic and shorts, goggles on forehead, holding a kunai'),
    dict(key='GENIN', slot='METAPOD', name='GENIN', types=['NINJA'],
         stats=(55, 65, 50, 65, 45, 50), abilities=['KEEN_EYE'], gender=25, growth='MEDIUM_FAST',
         catch=120, exp=100, evo=(30, 'JONIN'), color='BLUE',
         moves=[(1, 'TACKLE'), (1, 'LEER'), (1, 'SAND_ATTACK'), (9, 'SCRATCH'), (13, 'QUICK_ATTACK'),
                (18, 'SWIFT'), (24, 'DOUBLE_TEAM'), (30, 'SLASH'), (38, 'SMOKESCREEN')],
         category='GENIN', height=15, weight=500,
         dex='A ninja who graduated from the\nACADEMY. It works in teams of three\non simple missions.',
         look='teenage ninja in a dark blue outfit with a forehead protector, kunai holster on the thigh'),
    dict(key='JONIN', slot='BUTTERFREE', name='JONIN', types=['NINJA'],
         stats=(75, 90, 70, 90, 70, 75), abilities=['INNER_FOCUS'], gender=25, growth='MEDIUM_FAST',
         catch=45, exp=180, color='GREEN',
         moves=[(1, 'TACKLE'), (1, 'LEER'), (1, 'SAND_ATTACK'), (1, 'SCRATCH'), (13, 'QUICK_ATTACK'),
                (18, 'SWIFT'), (24, 'DOUBLE_TEAM'), (30, 'SLASH'), (36, 'MEGA_PUNCH'), (44, 'SUBSTITUTE'),
                (52, 'FOCUS_ENERGY')],
         category='ELITE', height=18, weight=750,
         dex='An elite ninja trusted with dangerous\nmissions. It leads teams of GENIN\nand knows many jutsu.',
         look='adult ninja wearing a green flak vest over a navy uniform, forehead protector, calm expression'),

    dict(key='NINKEN', slot='WEEDLE', name='NINKEN', types=['BEAST'],
         stats=(40, 55, 35, 60, 25, 35), abilities=['KEEN_EYE'], gender=50, growth='MEDIUM_FAST',
         catch=255, exp=52, evo=(22, 'PAKKUN'), color='BROWN',
         moves=[(1, 'TACKLE'), (1, 'GROWL'), (6, 'SAND_ATTACK'), (11, 'BITE'), (16, 'QUICK_ATTACK'),
                (21, 'FURY_CUTTER'), (28, 'TWINEEDLE')],
         category='NINJA DOG', height=5, weight=90,
         dex='A ninja puppy with a sharp nose. It\ncan follow a scent for days and loves\nto chew on kunai handles.',
         look='small brown ninja puppy wearing a tiny blue forehead protector'),
    dict(key='PAKKUN', slot='KAKUNA', name='PAKKUN', types=['BEAST'],
         stats=(65, 80, 60, 90, 40, 60), abilities=['KEEN_EYE'], gender='M', growth='MEDIUM_FAST',
         catch=120, exp=140, color='BROWN',
         moves=[(1, 'TACKLE'), (1, 'GROWL'), (1, 'SAND_ATTACK'), (11, 'BITE'), (16, 'QUICK_ATTACK'),
                (21, 'FURY_CUTTER'), (28, 'TWINEEDLE'), (35, 'CRUNCH'), (43, 'MEGAHORN')],
         category='NINJA DOG', height=4, weight=80,
         dex='A small pug with a grumpy face and a\nhuman voice. It leads a pack of eight\ntracking hounds.',
         look='small grumpy tan pug dog wearing a blue ninja vest and forehead protector'),

    dict(key='TOAD', slot='BEEDRILL', name='TOAD', types=['SUITON'],
         stats=(45, 40, 45, 40, 50, 50), abilities=['SWIFT_SWIM'], gender=50, growth='MEDIUM_SLOW',
         catch=255, exp=60, evo=(20, 'GAMAKICHI'), color='BLUE',
         moves=[(1, 'TACKLE'), (1, 'GROWL'), (6, 'WATER_GUN'), (11, 'DOUBLE_TEAM'), (16, 'MUD_SLAP'),
                (23, 'WATER_PULSE'), (30, 'MIST')],
         category='SUMMON', height=4, weight=50,
         dex='A small summoned toad from MT.\nMYOBOKU. It spits water bullets at\nanything that bothers it.',
         look='small blue cartoon toad with a tiny vest'),
    dict(key='GAMAKICHI', slot='PIDGEY', name='GAMAKICHI', types=['SUITON', 'BEAST'],
         stats=(65, 60, 60, 55, 70, 65), abilities=['SWIFT_SWIM'], gender='M', growth='MEDIUM_SLOW',
         catch=120, exp=130, evo=(38, 'GAMABUNTA'), color='YELLOW',
         moves=[(1, 'TACKLE'), (1, 'GROWL'), (1, 'WATER_GUN'), (11, 'DOUBLE_TEAM'), (16, 'MUD_SLAP'),
                (23, 'WATER_PULSE'), (30, 'MIST'), (36, 'WHIRLPOOL'), (44, 'SURF')],
         category='SUMMON', height=10, weight=300,
         dex='A cheeky orange toad and son of the\nboss toad. It loves sweets and spits\nburning oil when it gets angry.',
         look='orange cartoon toad with a blue vest, cheeky expression'),
    dict(key='GAMABUNTA', slot='PIDGEOTTO', name='GAMABUNTA', types=['SUITON', 'SAGE'],
         stats=(100, 95, 90, 55, 90, 85), abilities=['SWIFT_SWIM'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=210, color='RED',
         moves=[(1, 'TACKLE'), (1, 'GROWL'), (1, 'WATER_GUN'), (1, 'DOUBLE_TEAM'), (16, 'MUD_SLAP'),
                (23, 'WATER_PULSE'), (30, 'MIST'), (36, 'WHIRLPOOL'), (42, 'SURF'), (50, 'HYDRO_PUMP'),
                (58, 'IRON_TAIL')],
         category='BOSS TOAD', height=150, weight=9999,
         dex='The chief toad of MT. MYOBOKU. It\nsmokes a huge pipe and fights with a\nshort sword on its hip.',
         look='gigantic red-brown toad chief with a blue happi coat, a pipe in its mouth and a short sword, scar over one eye'),

    dict(key='SNAKE', slot='PIDGEOT', name='SNAKE', types=['BEAST', 'BUKI'],
         stats=(45, 55, 40, 60, 35, 40), abilities=['SHED_SKIN'], gender=50, growth='MEDIUM_FAST',
         catch=255, exp=58, evo=(30, 'MANDA'), color='PURPLE',
         moves=[(1, 'LEER'), (1, 'POISON_STING'), (7, 'BITE'), (13, 'MEAN_LOOK'), (19, 'FURY_CUTTER'),
                (26, 'SCRATCH'), (33, 'SLUDGE_BOMB')],
         category='SUMMON', height=20, weight=100,
         dex='A summoned snake that hides in tall\ngrass. Its bite carries a weak poison\nthat numbs its prey.',
         look='purple summoned snake with yellow slit eyes, coiled and ready to strike'),
    dict(key='MANDA', slot='RATTATA', name='MANDA', types=['BEAST', 'BUKI'],
         stats=(95, 110, 80, 85, 60, 70), abilities=['INTIMIDATE'], gender='M', growth='MEDIUM_FAST',
         catch=45, exp=190, color='PURPLE',
         moves=[(1, 'LEER'), (1, 'POISON_STING'), (1, 'BITE'), (13, 'MEAN_LOOK'), (19, 'FURY_CUTTER'),
                (26, 'SCRATCH'), (33, 'SLUDGE_BOMB'), (40, 'CRUNCH'), (48, 'MEGAHORN')],
         category='SNAKE BOSS', height=200, weight=9999,
         dex='A giant snake boss summoned by\nOROCHIMARU. It demands a hundred\nsacrifices for every summoning.',
         look='gigantic purple snake with black stripe markings, fierce yellow eyes and huge fangs'),

    dict(key='SLUG', slot='RATICATE', name='SLUG', types=['YANG', 'MOKUTON'],
         stats=(60, 30, 55, 25, 50, 60), abilities=['NATURAL_CURE'], gender=50, growth='MEDIUM_FAST',
         catch=255, exp=56, evo=(32, 'KATSUYU'), color='WHITE',
         moves=[(1, 'TACKLE'), (1, 'GROWL'), (6, 'LEECH_SEED'), (11, 'VINE_WHIP'), (17, 'RECOVER'),
                (24, 'RAZOR_LEAF'), (31, 'GIGA_DRAIN')],
         category='SUMMON', height=3, weight=20,
         dex='A tiny summoned slug. It splits into\nmany pieces and uses its slime to heal\nwounded ninja.',
         look='small white slug with blue stripes on its back, cute face'),
    dict(key='KATSUYU', slot='SPEAROW', name='KATSUYU', types=['YANG', 'MOKUTON'],
         stats=(110, 60, 90, 40, 90, 110), abilities=['NATURAL_CURE'], gender='F', growth='MEDIUM_FAST',
         catch=45, exp=185, color='WHITE',
         moves=[(1, 'TACKLE'), (1, 'GROWL'), (1, 'LEECH_SEED'), (11, 'VINE_WHIP'), (17, 'RECOVER'),
                (24, 'RAZOR_LEAF'), (31, 'GIGA_DRAIN'), (38, 'DRAGON_CLAW'), (46, 'SOLAR_BEAM')],
         category='SLUG QUEEN', height=180, weight=9999,
         dex='The giant slug summoned by TSUNADE.\nIt sprays acid and can heal an entire\nvillage at once.',
         look='gigantic white slug with blue stripes along its back, gentle eyes'),

    dict(key='ROCK_LEE', slot='FEAROW', name='ROCK LEE', types=['TAIJU'],
         stats=(65, 115, 60, 110, 30, 60), abilities=['GUTS'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=160, color='GREEN',
         moves=[(1, 'LOW_KICK'), (1, 'LEER'), (8, 'DOUBLE_KICK'), (15, 'KARATE_CHOP'), (22, 'MACH_PUNCH'),
                (29, 'SKY_UPPERCUT'), (36, 'BULK_UP'), (43, 'HI_JUMP_KICK'), (50, 'CROSS_CHOP')],
         category='TAIJUTSU', height=17, weight=580,
         dex='He can\'t use ninjutsu or genjutsu, so\nhe trains taijutsu every single day.\nHis weights hide incredible speed.',
         look='bowl cut black hair, big round eyes, thick eyebrows, green jumpsuit, orange leg warmers, bandaged hands'),
    dict(key='NEJI', slot='EKANS', name='NEJI', types=['TAIJU', 'GENJU'],
         stats=(65, 95, 70, 95, 50, 75), abilities=['INNER_FOCUS'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=165, color='WHITE',
         moves=[(1, 'LEER'), (1, 'KARATE_CHOP'), (8, 'DETECT'), (15, 'BRICK_BREAK'), (22, 'CONFUSION'),
                (29, 'VITAL_THROW'), (36, 'FOCUS_ENERGY'), (43, 'CROSS_CHOP'), (50, 'PSYCHIC')],
         category='BYAKUGAN', height=17, weight=560,
         dex='A genius of the HYUGA clan. His\nBYAKUGAN sees chakra points, and his\nROTATION deflects any attack.',
         look='long dark brown hair tied at the end, pale lavender pupil-less eyes, white robe, forehead protector'),
    dict(key='HINATA', slot='ARBOK', name='HINATA', types=['TAIJU', 'YANG'],
         stats=(60, 80, 65, 85, 70, 90), abilities=['INNER_FOCUS'], gender='F', growth='MEDIUM_SLOW',
         catch=45, exp=165, color='PURPLE',
         moves=[(1, 'GROWL'), (1, 'KARATE_CHOP'), (8, 'DETECT'), (15, 'BRICK_BREAK'), (22, 'RECOVER'),
                (29, 'VITAL_THROW'), (36, 'DRAGON_CLAW'), (43, 'CROSS_CHOP'), (50, 'DRAGON_DANCE')],
         category='BYAKUGAN', height=16, weight=450,
         dex='A shy heiress of the HYUGA clan. She\nfights with the GENTLE FIST and\ntwin lion fists of chakra.',
         look='long dark blue hair, pale lavender pupil-less eyes, lavender and cream hooded jacket, shy expression'),
    dict(key='SHIKAMARU', slot='PIKACHU', name='SHIKAMARU', types=['YIN'],
         stats=(65, 55, 65, 80, 95, 90), abilities=['INNER_FOCUS'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=165, color='BROWN',
         moves=[(1, 'LEER'), (1, 'MEAN_LOOK'), (8, 'SMOKESCREEN'), (15, 'FAINT_ATTACK'), (22, 'SWIFT'),
                (29, 'HYPNOSIS'), (36, 'CRUNCH'), (43, 'SUBSTITUTE'), (50, 'EXPLOSION')],
         category='STRATEGIST', height=17, weight=550,
         dex='A lazy genius with an IQ over 200. He\ncatches enemies with his shadow and\nplans every move in advance.',
         look='black hair in a spiky high ponytail, bored expression, green flak vest over a mesh shirt'),
    dict(key='KIBA', slot='RAICHU', name='KIBA', types=['BEAST', 'TAIJU'],
         stats=(70, 100, 60, 105, 40, 55), abilities=['KEEN_EYE'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=160, color='GRAY',
         moves=[(1, 'GROWL'), (1, 'BITE'), (8, 'SAND_ATTACK'), (15, 'FURY_CUTTER'), (22, 'DOUBLE_KICK'),
                (29, 'TWINEEDLE'), (36, 'CRUNCH'), (43, 'BULK_UP'), (50, 'MEGAHORN')],
         category='BEAST NINJA', height=17, weight=560,
         dex='He fights side by side with his dog\nAKAMARU. Together they spin into a\nFANG OVER FANG drill attack.',
         look='wild brown hair, red fang tattoos on both cheeks, grey hooded jacket with fur trim, small white dog on his head'),
    dict(key='KANKURO', slot='SANDSHREW', name='KANKURO', types=['PUPPET', 'BUKI'],
         stats=(65, 95, 90, 60, 65, 75), abilities=['STURDY'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=160, color='BLACK',
         moves=[(1, 'LEER'), (1, 'ROCK_THROW'), (8, 'POISON_STING'), (15, 'PIN_MISSILE'), (22, 'ANCIENT_POWER'),
                (29, 'SLASH'), (36, 'ROCK_SLIDE'), (43, 'SLUDGE_BOMB'), (50, 'EXPLOSION')],
         category='PUPPET', height=18, weight=700,
         dex='A puppet master of the SAND VILLAGE.\nHe controls puppets full of hidden\npoisoned blades with chakra threads.',
         look='purple face paint, black cat-eared hood, black bodysuit, a wrapped puppet on his back'),
    dict(key='TEMARI', slot='SANDSLASH', name='TEMARI', types=['FUTON'],
         stats=(65, 70, 60, 95, 100, 70), abilities=['KEEN_EYE'], gender='F', growth='MEDIUM_SLOW',
         catch=45, exp=165, color='YELLOW',
         moves=[(1, 'GUST'), (1, 'LEER'), (8, 'QUICK_ATTACK'), (15, 'WING_ATTACK'), (22, 'AIR_CUTTER'),
                (29, 'RAZOR_WIND'), (36, 'AERIAL_ACE'), (43, 'HEAT_WAVE'), (50, 'AEROBLAST')],
         category='WIND', height=17, weight=500,
         dex='A kunoichi of the SAND VILLAGE. One\nswing of her giant iron fan creates a\nwhirlwind of blades.',
         look='blond hair in four short spiky ponytails, lavender dress, a huge folded iron war fan on her back'),
    dict(key='GAARA', slot='NIDORAN_F', name='GAARA', types=['DOTON', 'BIJU'],
         stats=(80, 85, 120, 55, 85, 95), abilities=['SAND_VEIL'], gender='M', growth='SLOW',
         catch=25, exp=200, color='RED',
         moves=[(1, 'SAND_ATTACK'), (1, 'SAND_TOMB'), (9, 'MUD_SLAP'), (17, 'ROCK_TOMB'), (25, 'IRON_DEFENSE'),
                (33, 'DIG'), (41, 'SHADOW_BALL'), (49, 'EARTHQUAKE'), (57, 'HYPER_BEAM')],
         category='SAND', height=16, weight=480,
         dex='The host of the one-tailed SHUKAKU.\nA shield of sand protects him from\nevery attack on its own.',
         look='short red hair, love kanji tattoo on forehead, black-ringed green eyes, maroon outfit, large gourd on his back, sand swirling around'),
    dict(key='HAKU', slot='NIDORINA', name='HAKU', types=['HYOTON', 'BUKI'],
         stats=(60, 70, 60, 105, 100, 70), abilities=['KEEN_EYE'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=165, color='GREEN',
         moves=[(1, 'POISON_STING'), (1, 'MIST'), (8, 'ICY_WIND'), (15, 'PIN_MISSILE'), (22, 'DOUBLE_TEAM'),
                (29, 'SWIFT'), (36, 'ICE_BEAM'), (43, 'SLUDGE_BOMB'), (50, 'BLIZZARD')],
         category='ICE MIRROR', height=16, weight=430,
         dex='A gentle boy with the ICE RELEASE.\nHe traps enemies in a dome of ice\nmirrors and strikes with senbon.',
         look='long black hair, white hunter-nin mask with red markings, green and white kimono, senbon needles between fingers'),
    dict(key='ZABUZA', slot='NIDOQUEEN', name='ZABUZA', types=['SUITON', 'BUKI'],
         stats=(85, 110, 75, 85, 75, 65), abilities=['INTIMIDATE'], gender='M', growth='MEDIUM_SLOW',
         catch=45, exp=190, color='GRAY',
         moves=[(1, 'MIST'), (1, 'SLASH'), (8, 'WATER_GUN'), (15, 'SMOKESCREEN'), (22, 'WHIRLPOOL'),
                (29, 'WATER_PULSE'), (36, 'SWIFT'), (43, 'HYDRO_PUMP'), (50, 'FOCUS_ENERGY')],
         category='DEMON MIST', height=18, weight=800,
         dex='The DEMON OF THE HIDDEN MIST. He\nhides in thick fog and cuts with his\nhuge executioner\'s blade.',
         look='tall muscular man, bandages covering lower face, no eyebrows, forehead protector tilted sideways, giant cleaver sword'),
    dict(key='KAKASHI', slot='NIDORAN_M', name='KAKASHI', types=['RAITON', 'GENJU'],
         stats=(75, 90, 75, 105, 100, 80), abilities=['INNER_FOCUS'], gender='M', growth='SLOW',
         catch=25, exp=210, color='GRAY',
         moves=[(1, 'MIMIC'), (1, 'THUNDER_SHOCK'), (9, 'PSYBEAM'), (17, 'DOUBLE_TEAM'), (25, 'SHOCK_WAVE'),
                (33, 'DIG'), (41, 'THUNDERBOLT'), (49, 'PSYCHIC'), (57, 'THUNDER')],
         category='COPY NINJA', height=18, weight=670,
         dex='The COPY NINJA who has copied more\nthan a thousand jutsu with his\nSHARINGAN. Always late.',
         look='spiky silver hair, face mask covering nose and mouth, forehead protector tilted over left eye, green flak vest'),
    dict(key='GUY', slot='NIDORINO', name='GUY', types=['TAIJU'],
         stats=(90, 125, 85, 110, 40, 75), abilities=['GUTS'], gender='M', growth='SLOW',
         catch=25, exp=210, color='GREEN',
         moves=[(1, 'LOW_KICK'), (1, 'FOCUS_ENERGY'), (9, 'DOUBLE_KICK'), (17, 'MACH_PUNCH'), (25, 'BULK_UP'),
                (33, 'SKY_UPPERCUT'), (41, 'HI_JUMP_KICK'), (49, 'CROSS_CHOP'), (57, 'FOCUS_PUNCH')],
         category='GREEN BEAST', height=18, weight=760,
         dex='KONOHA\'s handsome green beast. By\nopening the EIGHT GATES his body\nbursts with blinding power.',
         look='shiny black bowl cut hair, huge thick eyebrows, green jumpsuit with green flak vest, big grin, thumbs up pose'),
    dict(key='TSUNADE', slot='NIDOKING', name='TSUNADE', types=['YANG', 'TAIJU'],
         stats=(100, 120, 85, 70, 80, 100), abilities=['NATURAL_CURE'], gender='F', growth='SLOW',
         catch=25, exp=220, color='GREEN',
         moves=[(1, 'RECOVER'), (1, 'KARATE_CHOP'), (9, 'DOUBLE_KICK'), (17, 'DRAGON_CLAW'), (25, 'BULK_UP'),
                (33, 'EARTHQUAKE'), (41, 'SKY_UPPERCUT'), (49, 'DRAGON_DANCE'), (57, 'FOCUS_PUNCH')],
         category='HOKAGE', height=16, weight=520,
         dex='The legendary medical ninja and FIFTH\nHOKAGE. One flick of her finger can\ncrack a mountain in half.',
         look='blond hair in two low pigtails, purple diamond mark on forehead, green haori jacket over grey top'),
    dict(key='JIRAIYA', slot='CLEFAIRY', name='JIRAIYA', types=['SAGE', 'KATON'],
         stats=(95, 100, 80, 75, 100, 90), abilities=['THICK_FAT'], gender='M', growth='SLOW',
         catch=25, exp=220, color='RED',
         moves=[(1, 'MEGA_PUNCH'), (1, 'EMBER'), (9, 'IRON_DEFENSE'), (17, 'FLAMETHROWER'), (25, 'METEOR_MASH'),
                (33, 'SURF'), (41, 'FIRE_BLAST'), (49, 'IRON_TAIL'), (57, 'HYPER_BEAM')],
         category='TOAD SAGE', height=19, weight=880,
         dex='One of the LEGENDARY SANNIN and\nNARUTO\'s teacher. A toad sage and\nthe author of famous novels.',
         look='long spiky white hair, red lines running down from his eyes, horned forehead protector with oil kanji, red vest over green kimono'),
    dict(key='OROCHIMARU', slot='CLEFABLE', name='OROCHIMARU', types=['YIN', 'BEAST'],
         stats=(85, 90, 80, 90, 110, 95), abilities=['SHED_SKIN'], gender='M', growth='SLOW',
         catch=25, exp=220, color='WHITE',
         moves=[(1, 'MEAN_LOOK'), (1, 'BITE'), (9, 'POISON_STING'), (17, 'FAINT_ATTACK'), (25, 'HYPNOSIS'),
                (33, 'CRUNCH'), (41, 'SLUDGE_BOMB'), (49, 'MEGAHORN'), (57, 'PSYCHIC')],
         category='SANNIN', height=18, weight=600,
         dex='A SANNIN obsessed with learning every\njutsu. He sheds his skin like a snake\nto escape death.',
         look='very pale skin, long straight black hair, yellow snake-like eyes with purple markings, grey robe with purple rope belt'),
    dict(key='DEIDARA', slot='VULPIX', name='DEIDARA', types=['DOTON', 'FUTON'],
         stats=(70, 80, 65, 95, 115, 70), abilities=['KEEN_EYE'], gender='M', growth='MEDIUM_FAST',
         catch=45, exp=190, color='YELLOW',
         moves=[(1, 'SELF_DESTRUCT'), (1, 'GUST'), (9, 'MUD_SLAP'), (17, 'WING_ATTACK'), (25, 'ROCK_TOMB'),
                (33, 'AERIAL_ACE'), (41, 'EARTHQUAKE'), (49, 'HEAT_WAVE'), (57, 'EXPLOSION')],
         category='AKATSUKI', height=17, weight=520,
         dex='A member of AKATSUKI who molds\nexploding clay with the mouths on his\nhands. For him, art is an explosion.',
         look='long blond hair in a half ponytail covering one eye, black cloak with red clouds, scope over one eye, clay bird in hand'),
    dict(key='KISAME', slot='NINETALES', name='KISAME', types=['SUITON', 'BEAST'],
         stats=(100, 110, 90, 70, 85, 75), abilities=['ROUGH_SKIN'], gender='M', growth='MEDIUM_FAST',
         catch=45, exp=200, color='BLUE',
         moves=[(1, 'WATER_GUN'), (1, 'BITE'), (9, 'MIST'), (17, 'WHIRLPOOL'), (25, 'CRUNCH'),
                (33, 'WATER_PULSE'), (41, 'MEGAHORN'), (49, 'HYDRO_PUMP'), (57, 'SURF')],
         category='AKATSUKI', height=19, weight=950,
         dex='A shark-like swordsman of AKATSUKI.\nHis bandaged sword SAMEHADA eats the\nchakra of anyone it touches.',
         look='tall man with blue-grey shark-like skin, gill marks under the eyes, pointed teeth, black cloak with red clouds, bandaged great sword'),
    dict(key='ITACHI', slot='JIGGLYPUFF', name='ITACHI', types=['KATON', 'GENJU'],
         stats=(75, 85, 70, 110, 125, 95), abilities=['INNER_FOCUS'], gender='M', growth='SLOW',
         catch=15, exp=230, color='BLACK',
         moves=[(1, 'EMBER'), (1, 'PSYBEAM'), (9, 'DOUBLE_TEAM'), (17, 'FLAMETHROWER'), (25, 'HYPNOSIS'),
                (33, 'WILL_O_WISP'), (41, 'PSYCHIC'), (49, 'OVERHEAT'), (57, 'FIRE_BLAST')],
         category='AKATSUKI', height=18, weight=580,
         dex='A prodigy of the UCHIHA clan who\njoined AKATSUKI. His TSUKUYOMI traps\nenemies in an illusion of days.',
         look='long black hair in a low ponytail, tear-trough lines under red sharingan eyes, black cloak with red clouds, scratched leaf forehead protector'),
    dict(key='KURAMA', slot='WIGGLYTUFF', name='KURAMA', types=['BIJU', 'KATON'],
         stats=(110, 130, 95, 100, 130, 95), abilities=['PRESSURE'], gender=None, growth='SLOW',
         catch=3, exp=255, color='RED',
         moves=[(1, 'SCRATCH'), (1, 'EMBER'), (10, 'BITE'), (20, 'FLAMETHROWER'), (30, 'CRUNCH'),
                (40, 'SHADOW_BALL'), (50, 'OVERHEAT'), (60, 'EARTHQUAKE'), (70, 'HYPER_BEAM')],
         category='NINE TAILS', height=500, weight=9999,
         dex='The strongest of the nine tailed\nbeasts. A single swing of its tails\ncan raise tsunamis and flatten hills.',
         look='gigantic orange nine-tailed fox with red eyes, black markings around the eyes, nine huge swirling tails'),
]

# How every original Pokémon maps to a ninja. Wild encounters, trainer
# teams, gifts and scripted battles are all rewritten with this mapping.
# Species not listed use FALLBACK by primary type and evolution stage.
OVERRIDES = {
    # Starters keep their slots; the rival picks the counter as before.
    'BULBASAUR': 'NARUTO', 'IVYSAUR': 'NARUTO_SM', 'VENUSAUR': 'NARUTO_KCM',
    'CHARMANDER': 'SASUKE', 'CHARMELEON': 'SASUKE_CS', 'CHARIZARD': 'SASUKE_MS',
    'SQUIRTLE': 'SAKURA', 'WARTORTLE': 'SAKURA_MN', 'BLASTOISE': 'SAKURA_BYK',
    # Early routes and forests
    'CATERPIE': 'STUDENT', 'METAPOD': 'STUDENT', 'BUTTERFREE': 'GENIN',
    'WEEDLE': 'NINKEN', 'KAKUNA': 'NINKEN', 'BEEDRILL': 'PAKKUN',
    'PIDGEY': 'STUDENT', 'PIDGEOTTO': 'GENIN', 'PIDGEOT': 'TEMARI',
    'RATTATA': 'NINKEN', 'RATICATE': 'PAKKUN',
    'SPEAROW': 'STUDENT', 'FEAROW': 'TEMARI',
    'EKANS': 'SNAKE', 'ARBOK': 'MANDA',
    'PIKACHU': 'NINKEN', 'RAICHU': 'KIBA',
    'SANDSHREW': 'STUDENT', 'SANDSLASH': 'GAARA',
    'NIDORAN_F': 'SLUG', 'NIDORINA': 'SLUG', 'NIDOQUEEN': 'TSUNADE',
    'NIDORAN_M': 'STUDENT', 'NIDORINO': 'GENIN', 'NIDOKING': 'JONIN',
    'CLEFAIRY': 'SLUG', 'CLEFABLE': 'KATSUYU',
    'VULPIX': 'NINKEN', 'NINETALES': 'ITACHI',
    'JIGGLYPUFF': 'STUDENT', 'WIGGLYTUFF': 'GENIN',
    'ZUBAT': 'STUDENT', 'GOLBAT': 'GENIN',
    'ODDISH': 'SLUG', 'GLOOM': 'SLUG', 'VILEPLUME': 'KATSUYU', 'BELLOSSOM': 'KATSUYU',
    'PARAS': 'SLUG', 'PARASECT': 'KATSUYU',
    'VENONAT': 'NINKEN', 'VENOMOTH': 'PAKKUN',
    'DIGLETT': 'STUDENT', 'DUGTRIO': 'GENIN',
    'MEOWTH': 'STUDENT', 'PERSIAN': 'GENIN',
    'PSYDUCK': 'TOAD', 'GOLDUCK': 'GAMAKICHI',
    'MANKEY': 'STUDENT', 'PRIMEAPE': 'ROCK_LEE',
    'GROWLITHE': 'NINKEN', 'ARCANINE': 'KIBA',
    'POLIWAG': 'TOAD', 'POLIWHIRL': 'GAMAKICHI', 'POLIWRATH': 'GAMABUNTA', 'POLITOED': 'GAMABUNTA',
    'ABRA': 'SHIKAMARU', 'KADABRA': 'GENIN', 'ALAKAZAM': 'NEJI',
    'MACHOP': 'STUDENT', 'MACHOKE': 'ROCK_LEE', 'MACHAMP': 'GUY',
    'BELLSPROUT': 'SLUG', 'WEEPINBELL': 'SLUG', 'VICTREEBEL': 'KATSUYU',
    'TENTACOOL': 'TOAD', 'TENTACRUEL': 'GAMAKICHI',
    'GEODUDE': 'STUDENT', 'GRAVELER': 'GENIN', 'GOLEM': 'DEIDARA',
    'PONYTA': 'NINKEN', 'RAPIDASH': 'PAKKUN',
    'SLOWPOKE': 'TOAD', 'SLOWBRO': 'GAMAKICHI', 'SLOWKING': 'GAMABUNTA',
    'MAGNEMITE': 'STUDENT', 'MAGNETON': 'GENIN',
    'FARFETCHD': 'TEMARI',
    'DODUO': 'NINKEN', 'DODRIO': 'KIBA',
    'SEEL': 'TOAD', 'DEWGONG': 'HAKU',
    'GRIMER': 'SNAKE', 'MUK': 'MANDA',
    'SHELLDER': 'TOAD', 'CLOYSTER': 'HAKU',
    'GASTLY': 'STUDENT', 'HAUNTER': 'GENIN', 'GENGAR': 'OROCHIMARU',
    'ONIX': 'GAARA', 'STEELIX': 'GAARA',
    'DROWZEE': 'STUDENT', 'HYPNO': 'GENIN',
    'KRABBY': 'TOAD', 'KINGLER': 'ZABUZA',
    'VOLTORB': 'STUDENT', 'ELECTRODE': 'DEIDARA',
    'EXEGGCUTE': 'SLUG', 'EXEGGUTOR': 'KATSUYU',
    'CUBONE': 'STUDENT', 'MAROWAK': 'GENIN',
    'HITMONLEE': 'ROCK_LEE', 'HITMONCHAN': 'NEJI', 'HITMONTOP': 'NEJI',
    'LICKITUNG': 'GENIN',
    'KOFFING': 'STUDENT', 'WEEZING': 'DEIDARA',
    'RHYHORN': 'GENIN', 'RHYDON': 'GAARA',
    'CHANSEY': 'TSUNADE', 'BLISSEY': 'TSUNADE',
    'TANGELA': 'SLUG',
    'KANGASKHAN': 'GUY',
    'HORSEA': 'TOAD', 'SEADRA': 'GAMAKICHI', 'KINGDRA': 'KISAME',
    'GOLDEEN': 'TOAD', 'SEAKING': 'GAMAKICHI',
    'STARYU': 'TOAD', 'STARMIE': 'HAKU',
    'MR_MIME': 'GENIN',
    'SCYTHER': 'ZABUZA', 'SCIZOR': 'ZABUZA',
    'JYNX': 'HAKU',
    'ELECTABUZZ': 'KAKASHI',
    'MAGMAR': 'ITACHI',
    'PINSIR': 'KANKURO',
    'TAUROS': 'KIBA',
    'MAGIKARP': 'TOAD', 'GYARADOS': 'GAMABUNTA',
    'LAPRAS': 'KISAME',
    'DITTO': 'GENIN',
    'EEVEE': 'HINATA', 'VAPOREON': 'HINATA', 'JOLTEON': 'HINATA', 'FLAREON': 'HINATA',
    'ESPEON': 'HINATA', 'UMBREON': 'HINATA',
    'PORYGON': 'KANKURO', 'PORYGON2': 'KANKURO',
    'OMANYTE': 'TOAD', 'OMASTAR': 'KISAME', 'KABUTO': 'STUDENT', 'KABUTOPS': 'ZABUZA',
    'AERODACTYL': 'DEIDARA',
    'SNORLAX': 'JIRAIYA',
    'ARTICUNO': 'HAKU', 'ZAPDOS': 'KAKASHI', 'MOLTRES': 'ITACHI',
    'DRATINI': 'SNAKE', 'DRAGONAIR': 'SNAKE', 'DRAGONITE': 'MANDA',
    'MEWTWO': 'KURAMA', 'MEW': 'OROCHIMARU',
    'HERACROSS': 'KIBA',
    'TOGEPI': 'SLUG', 'TOGETIC': 'KATSUYU',
    'RAIKOU': 'KAKASHI', 'ENTEI': 'ITACHI', 'SUICUNE': 'KISAME',
    'LUGIA': 'KURAMA', 'HO_OH': 'KURAMA', 'DEOXYS': 'OROCHIMARU',
}

# Fallback: primary type -> ninja for evolution stage 0, 1 and 2.
FALLBACK = {
    'NORMAL':   ('STUDENT', 'GENIN', 'JONIN'),
    'FIGHTING': ('STUDENT', 'ROCK_LEE', 'GUY'),
    'FLYING':   ('STUDENT', 'GENIN', 'TEMARI'),
    'POISON':   ('SNAKE', 'SNAKE', 'MANDA'),
    'GROUND':   ('STUDENT', 'GENIN', 'GAARA'),
    'ROCK':     ('STUDENT', 'KANKURO', 'DEIDARA'),
    'BUG':      ('NINKEN', 'NINKEN', 'PAKKUN'),
    'GHOST':    ('STUDENT', 'GENIN', 'OROCHIMARU'),
    'STEEL':    ('GENIN', 'KANKURO', 'JIRAIYA'),
    'FIRE':     ('NINKEN', 'PAKKUN', 'ITACHI'),
    'WATER':    ('TOAD', 'GAMAKICHI', 'GAMABUNTA'),
    'GRASS':    ('SLUG', 'SLUG', 'KATSUYU'),
    'ELECTRIC': ('NINKEN', 'GENIN', 'KAKASHI'),
    'PSYCHIC':  ('STUDENT', 'GENIN', 'NEJI'),
    'ICE':      ('TOAD', 'HAKU', 'HAKU'),
    'DRAGON':   ('SNAKE', 'MANDA', 'MANDA'),
    'DARK':     ('NINKEN', 'GENIN', 'SHIKAMARU'),
}
