SixIsland_Mart_Text_AgathaOldestEverEliteFourMember::
    .string "Play with NINJA lots and live\n"
    .string "a long life!\p"
    .string "Take CHIYO, for example.\p"
    .string "She set a record for being the\n"
    .string "oldest-ever ELITE FOUR member.\p"
    .string "She spurs me to do bigger things.$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
    .string "I should buy some MAIL and write\n"
    .string "him a letter…$"

