CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "That BILL!\p"
    .string "I heard that he'll do whatever it\n"
    .string "takes to get rare NINJA.\p"
    .string "He's not above doing all sorts\n"
    .string "of things, I've heard.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "Have you heard about BILL?\p"
    .string "Everyone calls him a POKéMANIAC!\p"
    .string "I think people are just jealous of\n"
    .string "BILL, though.\p"
    .string "Who wouldn't want to boast about\n"
    .string "their NINJA?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "BILL has lots of NINJA!\n"
    .string "He collects rare ones, too!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "Why don't you go upstairs and try\n"
    .string "trading NINJA with your friends?\p"
    .string "You could get a lot more variety\n"
    .string "by trading.\p"
    .string "The NINJA you get in trades grow\n"
    .string "quickly, too.$"

